backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "src/images"
public_folder: "/images"
collections:
  - name: "events"
    label: "Events"
    folder: "src/meetings"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Starts at", name: "start", widget: "datetime" }
      - { label: "Ends at", name: "end", widget: "datetime" }
