backend:
  name: git-gateway
  branch: tech/netlify-cms-integration # Update this to main branch

publish_mode: editorial_workflow
media_folder: "src/images"
public_folder: "/images"

collections:
  - name: "events"
    label: "Events"
    folder: "src/meetings"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Starts at", name: "start", widget: "datetime" }
      - { label: "Ends at", name: "end", widget: "datetime" }
      - {
          label: "Groups",
          name: "groups",
          widget: "relation",
          multiple: true,
          collection: "groups",
          value_field: "{{slug}}",
          search_fields: ["title"],
          display_fields: ["title"],
        }
      - {
          label: "Navigation",
          name: "eleventyNavigation",
          widget: "object",
          summary: "{{ field.name }}: {{ fields.parent }}",
          fields:
            [
              {
                label: "Parent",
                name: "parent",
                widget: "relation",
                multiple: false,
                collection: "groups",
                value_field: "{{slug}}",
                search_fields: ["title"],
                display_fields: ["title"],
                hint: "This is the group you want to assign to the breadcrumb",
              },
            ],
        }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Invitation link", name: "invitation", widget: "string" }
      - { label: "Agenda", name: "agenda", widget: "markdown" }
      - { label: "Minutes", name: "minutes", widget: "markdown" }

  - name: "groups"
    label: "Groups"
    folder: "src/groups"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }

  - name: "protocols"
    label: "Protocols"
    folder: "src/protocols"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Groups",
          name: "groups",
          widget: "relation",
          multiple: true,
          collection: "groups",
          value_field: "{{slug}}",
          search_fields: ["title"],
          display_fields: ["title"],
        }

  - name: "advice"
    label: "Advice Documents"
    folder: "src/advice"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Groups",
          name: "groups",
          widget: "relation",
          multiple: true,
          collection: "groups",
          value_field: "{{slug}}",
          search_fields: ["title"],
          display_fields: ["title"],
        }

  - name: "reporting-standards"
    label: "Reporting Standards"
    folder: "src/reporting-standards"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Groups",
          name: "groups",
          widget: "relation",
          multiple: true,
          collection: "groups",
          value_field: "{{slug}}",
          search_fields: ["title"],
          display_fields: ["title"],
        }

  - name: "procedures"
    label: "Procedural Documents"
    folder: "src/procedures"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Groups",
          name: "groups",
          widget: "relation",
          multiple: true,
          collection: "groups",
          value_field: "{{slug}}",
          search_fields: ["title"],
          display_fields: ["title"],
        }

  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "src/pages"
    create: true
    path: "{{categories.0}}/{{slug}}"
    nested:
      depth: 5
      summary: "{{title}}"
    view_groups:
      - label: Categories
        field: categories
    fields:
      - { label: Title, name: title, widget: string }
      - {
          label: "Categories",
          name: "categories",
          widget: "relation",
          multiple: true,
          collection: "categories",
          value_field: "{{slug}}",
          search_fields: ["title"],
          display_fields: ["title"],
          hint: "The first category will be used to build up the URL",
        }
      - {
          label: "Parent",
          name: "parent",
          widget: "relation",
          multiple: true,
          collection: "pages",
          value_field: "{{slug}}",
          search_fields: ["title"],
          display_fields: ["title"],
          hint: "If this page is a child of another, please provide the parent here",
        }
      - {
          label: "Tags",
          name: "tags",
          widget: "relation",
          multiple: true,
          collection: "tags",
          value_field: "{{slug}}",
          search_fields: ["title"],
          display_fields: ["title"],
        }
      - {
          label: Is Mini Hub?,
          name: is_mini_hub,
          widget: boolean,
          required: false,
          default: false,
        }
      - { label: Sub-title, name: subtitle, widget: string }
      - { label: Excerpt, name: excerpt, widget: text }
      - { label: Sidebar, name: sidebar, widget: boolean, required: false }
      - {
          label: Table of Contents,
          name: toc,
          widget: boolean,
          required: false,
        }
      - { label: Body, name: body, widget: markdown }

  - name: "categories"
    label: "Categories"
    label_singular: "Category"
    folder: "src/categories"
    create: true
    editor:
      preview: false
    fields:
      - { label: Title, name: title, widget: string }

  - name: "tags"
    label: "Tags"
    label_singular: "Tag"
    folder: "src/tags"
    create: true
    editor:
      preview: false
    fields:
      - { label: Title, name: title, widget: string }
